[env]
TERM = "xterm-256color"

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Buttonless"

option_as_alt = "Both"

[font]

normal.family = "MesloLGS NF"
bold.family = "MesloLGS NF"
italic.family = "MesloLGS NF"
bold_italic.family = "MesloLGS NF"

size = 19.0
